### ISSUE TITLE
Tester

### ISSUE THREAD

**Issue by jamesturnernz** [GaloyMoney/blink-woocommerce#1]
Hi, big user of Blink wallet.

Would love to test on our Wordpress WooCommerce Shop.
Thanks

**Comment by jamesturnernz** [comment]
Hi, any updates on this?

Rolling out the new shopping cart now.  Keen to be testing if things are ready.  Thank you.

**Comment by dolcalmi** [comment]
> Hi, any updates on this?
> 
> Rolling out the new shopping cart now. Keen to be testing if things are ready. Thank you.

we are waiting for this PR https://github.com/GaloyMoney/blink/pull/4363 to be able to deploy... I will let you know once it is in prod

**Comment by jamesturnernz** [comment]
Any updates? 
Thank you

**Comment by dolcalmi** [comment]
> Any updates? Thank you

Hi James, WP review took more than expected but it was published today https://wordpress.org/plugins/blink-for-woocommerce/ (It's still in beta, so any feedback or suggestions will be appreciated)
